"""Turns the cached addresses into the coordinates the parcel map draws with.

Every plot has an official address, so its position is surveyed rather than
measured off a drawing. Felleshuset is number 50 and is kept apart as a landmark.

Run from the repository root:  python scripts/build-parcel-locations.py
"""

import json
from pathlib import Path

CACHE = Path("scripts/strandhagane-addresses.json")
OUT = Path("apps/admin/src/components/parcels/parcel-locations.ts")

addresses = {int(n): p for n, p in json.loads(CACHE.read_text()).items()}

hall = addresses.pop(50)
plots = dict(sorted(addresses.items()))

lats = [lat for lat, _ in plots.values()]
lons = [lon for _, lon in plots.values()]

lines = [
    "/**",
    " * Where every parcel is, from Kartverket's address register: each plot is a",
    " * numbered address in Strandhagane, and Felleshuset is number 50.",
    " *",
    " * Generated by scripts/build-parcel-locations.py. Edit that, not this.",
    " */",
    "",
    "export type ParcelLocation = { number: number; lat: number; lon: number };",
    "",
    "/** Felleshuset, which the map opens centred on. */",
    f"export const SITE_CENTRE = {{ lat: {round(sum(lats) / len(lats), 6)}, lon: {round(sum(lons) / len(lons), 6)} }};",
    "",
    "/** The corners the map fits to, with a little air around the outermost plots. */",
    "export const SITE_BOUNDS = {",
    f"  north: {round(max(lats) + 0.0004, 6)},",
    f"  south: {round(min(lats) - 0.0004, 6)},",
    f"  east: {round(max(lons) + 0.0008, 6)},",
    f"  west: {round(min(lons) - 0.0008, 6)},",
    "};",
    "",
    "/** The common house, as a landmark on the map. */",
    f"export const HALL = {{ lat: {hall[0]}, lon: {hall[1]} }};",
    "",
    "export const PARCEL_LOCATIONS: ParcelLocation[] = [",
]

for number, (lat, lon) in plots.items():
    lines.append(f"  {{ number: {number}, lat: {lat}, lon: {lon} }},")

lines.append("];")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT} with {len(plots)} plots")
