/**
 * Where every parcel is, from Kartverket's address register: each plot is a
 * numbered address in Strandhagane, and Felleshuset is number 50.
 *
 * Generated by scripts/build-parcel-locations.py. Edit that, not this.
 */

export type ParcelLocation = { number: number; lat: number; lon: number };

/** Felleshuset, which the map opens centred on. */
export const SITE_CENTRE = { lat: 58.874869, lon: 5.588566 };

/** The corners the map fits to, with a little air around the outermost plots. */
export const SITE_BOUNDS = {
  north: 58.876044,
  south: 58.873421,
  east: 5.590779,
  west: 5.585891,
};

/** The common house, as a landmark on the map. */
export const HALL = { lat: 58.8750317, lon: 5.5868713 };

export const PARCEL_LOCATIONS: ParcelLocation[] = [
  { number: 1, lat: 58.8756445, lon: 5.5881196 },
  { number: 2, lat: 58.8755547, lon: 5.588394 },
  { number: 3, lat: 58.8754542, lon: 5.5887424 },
  { number: 4, lat: 58.8755721, lon: 5.5877969 },
  { number: 5, lat: 58.875424, lon: 5.5880424 },
  { number: 6, lat: 58.8753691, lon: 5.5884453 },
  { number: 7, lat: 58.8752717, lon: 5.588809 },
  { number: 8, lat: 58.8752163, lon: 5.589231 },
  { number: 9, lat: 58.8751034, lon: 5.5894817 },
  { number: 10, lat: 58.8749785, lon: 5.589822 },
  { number: 11, lat: 58.8748631, lon: 5.5899792 },
  { number: 12, lat: 58.8752313, lon: 5.5881638 },
  { number: 13, lat: 58.875131, lon: 5.5885191 },
  { number: 14, lat: 58.8751068, lon: 5.5888287 },
  { number: 15, lat: 58.8750034, lon: 5.5892017 },
  { number: 16, lat: 58.8748704, lon: 5.5895758 },
  { number: 17, lat: 58.8746881, lon: 5.5898541 },
  { number: 18, lat: 58.8754263, lon: 5.5871778 },
  { number: 19, lat: 58.8753982, lon: 5.5875086 },
  { number: 20, lat: 58.8754254, lon: 5.5868359 },
  { number: 21, lat: 58.8752727, lon: 5.5870766 },
  { number: 22, lat: 58.8752436, lon: 5.5866907 },
  { number: 23, lat: 58.8752076, lon: 5.5876766 },
  { number: 24, lat: 58.8750436, lon: 5.5880348 },
  { number: 25, lat: 58.8749566, lon: 5.5883801 },
  { number: 26, lat: 58.8748771, lon: 5.5887732 },
  { number: 27, lat: 58.8747882, lon: 5.5891864 },
  { number: 28, lat: 58.8745347, lon: 5.589798 },
  { number: 29, lat: 58.8751444, lon: 5.58736 },
  { number: 30, lat: 58.8750195, lon: 5.5875997 },
  { number: 31, lat: 58.8749132, lon: 5.5878966 },
  { number: 32, lat: 58.8748, lon: 5.5882046 },
  { number: 33, lat: 58.8747142, lon: 5.5884959 },
  { number: 34, lat: 58.8747123, lon: 5.5889318 },
  { number: 35, lat: 58.8745612, lon: 5.5892001 },
  { number: 36, lat: 58.8745611, lon: 5.5887887 },
  { number: 37, lat: 58.8743953, lon: 5.5892841 },
  { number: 38, lat: 58.8742992, lon: 5.5896268 },
  { number: 39, lat: 58.8741332, lon: 5.5894315 },
  { number: 40, lat: 58.8739871, lon: 5.5893816 },
  { number: 41, lat: 58.873821, lon: 5.5892869 },
  { number: 42, lat: 58.8739326, lon: 5.5889513 },
  { number: 43, lat: 58.8740806, lon: 5.5887007 },
  { number: 44, lat: 58.8742482, lon: 5.5887172 },
  { number: 45, lat: 58.8741793, lon: 5.5883213 },
  { number: 46, lat: 58.8743681, lon: 5.5883218 },
  { number: 47, lat: 58.8743181, lon: 5.5879622 },
];
